#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Unsupported number of parameters"
  exit 1
fi

interface=$1

# Map interface names from previous Debian releases
if [ "$interface" = "eth0" ]; then
  interface="enp0s3"
elif [ "$interface" = "eth1" ]; then
  interface="enp6s0"
fi

ip link show dev "$interface"
