#! /bin/sh

#
# postinst for the endor-paragon-vi project.
# 
# We are installing the VI, so we are going to force the
# instrument controller to connect to the VI.  We do this
# by creating a softlink to point 
# /opt/bin/calnex.endor.instrument.controller to
# /opt/bin/calnex.endor.instrument.controller.virtualinstrument
#

cd /opt/bin

if [ -e /opt/bin/calnex.endor.instrument.controller ]; then
    rm /opt/bin/calnex.endor.instrument.controller
fi

ln -s /opt/bin/calnex.endor.instrument.controller.virtualinstrument /opt/bin/calnex.endor.instrument.controller
