#! /bin/sh

screen -dmS LOADING python3 /sbin/loading_server > /dev/null

LOADED=1

while [ -n $LOADED ]
do
	wget -qO- localhost:8000 > /dev/null
	LOADED=$?
	sleep 0.2
done

iptables -t nat -R PREROUTING 1 -i eth0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8000
pkill -f 'python3 /sbin/loading_server'