#! /bin/sh
### BEGIN INIT INFO
# Provides:          Loading webserver
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: script used to launch the python based loading screen
# Description:
### END INIT INFO

/sbin/loading_server &