#! /bin/sh
### BEGIN INIT INFO
# Provides:          init_server
# Required-Start:    
# Required-Stop:
# Should-Start:
# Default-Start:     
# Default-Stop:      
# Short-Description: script used to launch the python based loading screen
### END INIT INFO

/sbin/loading_server &
exit 0
