#! /bin/sh

if test -z "${REAL_OPT_DIR}"; then
# next line to be replaced according to OPTWARE_TARGET
REAL_OPT_DIR=
fi

case "$1" in
    start)
        echo "Starting Optware."
        if test -n "${REAL_OPT_DIR}"; then
            if ! grep ' /opt ' /proc/mounts >/dev/null 2>&1 ; then
                mkdir -p /opt
                mount -o bind ${REAL_OPT_DIR} /opt
            fi
        fi
	
	# Default repo location to network
	echo "src/gz local file://srv/tftp/optware"       > /opt/etc/ipkg/cross-feed.conf
	
	# Call USB script, it should make no change
	# if no USB is present
	/bin/optwareUSB add
	
	if [ -x /etc/init.d/S00SystemConfiguration ]; then
		/etc/init.d/S00SystemConfiguration
	fi
	if [ -x /etc/init.d/S00SystemLoading ]; then
		/etc/init.d/S00SystemLoading start
	fi
    if [ -x /etc/init.d/S90fix-interfaces ]; then
        /etc/init.d/S90fix-interfaces
    fi
	[ -x /opt/etc/rc.optware ] && su - calnex -c '/opt/etc/rc.optware start'
    ;;
    reconfig)
	true
    ;;
    stop)
        echo "Shutting down Optware."
	true
    ;;
    *)
        echo "Usage: $0 {start|stop|reconfig}"
        exit 1
esac

exit 0
