#! /bin/sh

if test -z "${REAL_OPT_DIR}"; then
# next line to be replaced according to OPTWARE_TARGET
REAL_OPT_DIR=
fi

case "$1" in
    start)
        if [ ! -d /tmp/embedded ]; then
            mkdir -p /tmp/embedded
            chown calnex:calnex /tmp/embedded
            service nfs-kernel-server restart
        fi

        echo "Starting Optware."
        if test -n "${REAL_OPT_DIR}"; then
            if ! grep ' /opt ' /proc/mounts >/dev/null 2>&1 ; then
                mkdir -p /opt
                mount -o bind ${REAL_OPT_DIR} /opt
            fi
        fi
	
        # Default repo location to network
        echo "src/gz local file://srv/tftp/optware"       > /opt/etc/ipkg/cross-feed.conf
        
        # Call USB script, it should make no change
        # if no USB is present
        /bin/optwareUSB add
        
        if [ -x /etc/init.d/S00SystemConfiguration ]; then
            /etc/init.d/S00SystemConfiguration
        fi
        if [ -x /etc/init.d/S00SystemLoading ]; then
            /etc/init.d/S00SystemLoading start
        fi

        [ -x /etc/init.d/S90fix-interfaces ] && /etc/init.d/S90fix-interfaces

        if test -b /dev/vda && ! test -d /home/calnex/Calnex100G/Persist; then 
            echo "Mounting persistent log directory /dev/vda1"
            mkdir -p /home/calnex/Calnex100G/Persist; 
            chown -R calnex:calnex /home/calnex/Calnex100G
            mount /dev/vda1 /home/calnex/Calnex100G/Persist; 

            echo "Linking LogFiles directory to persistent log directory"
            if test -d /home/calnex/Calnex100G/Logs/; then
                rm -rf /home/calnex/Calnex100G/Logs
            fi
            su - calnex -c 'ln -s /home/calnex/Calnex100G/Persist /home/calnex/Calnex100G/Logs'
        fi

        [ -x /opt/etc/rc.optware ] && su - calnex -c '/opt/etc/rc.optware start'
        ;;
    reconfig)
        true
    ;;
    stop)
        echo "Shutting down Optware."
	    true
    ;;
    *)
        echo "Usage: $0 {start|stop|reconfig}"
        exit 1
esac

exit 0
