#! /bin/sh

if test -z "${REAL_OPT_DIR}"; then
# next line to be replaced according to OPTWARE_TARGET
REAL_OPT_DIR=
fi

case "$1" in
    start)
        echo "Starting Optware." | tee -a /var/log/SystemConfig

        [ -x /opt/etc/hooks/root.preopt ] && /opt/etc/hooks/root.premount

        if test -n "${REAL_OPT_DIR}"; then
            if ! grep ' /opt ' /proc/mounts >/dev/null 2>&1 ; then
                mkdir -p /opt
                mount -o bind "${REAL_OPT_DIR}" /opt
            fi
        fi

        if grep "clnx-no-setup" /proc/cmdline 2>/dev/null; then
            echo "Boot paramater clnx-no-setup set. Not starting optware or configuring system" | tee -a /var/log/SystemConfig
            exit 0
        fi

        [ -x /opt/etc/hooks/root.preopt ] && /opt/etc/hooks/root.preconfig

        # Default repo location to network
        echo "src/gz local file://home/.optware/srv/tftp/optware" > /opt/etc/ipkg/cross-feed.conf
        
        # Call USB script, it should make no change
        # if no USB is present
        /bin/optwareUSB add

        if [ -x /etc/init.d/S00SystemConfiguration ]; then
            /etc/init.d/S00SystemConfiguration
        fi        
        if [ -x /etc/init.d/S01SystemConfiguration ]; then
            /etc/init.d/S01SystemConfiguration
        fi
        if [ -x /etc/init.d/S00SystemLoading ]; then
            /etc/init.d/S00SystemLoading start
        fi

        # Fix the network interfaces config which is prone to being incorrect on VM's
        [ -x /etc/init.d/S90fix-interfaces ] && /etc/init.d/S90fix-interfaces

        if grep "clnx-no-optware" /proc/cmdline 2>/dev/null; then
            echo "Boot paramater clnx-no-optware set. Not starting optware" | tee -a /var/log/SystemConfig
            exit 0
        fi

        # Some pre optware dev script hooks
        [ -x /opt/etc/hooks/root.preopt ] && /opt/etc/hooks/root.preopt
        [ -x /opt/etc/hooks/user.preopt ] && su - calnex -c '/opt/etc/hooks/user.preopt'

        # Start all optware packages
        [ -x /opt/etc/rc.optware ] && su - calnex -c '/opt/etc/rc.optware start'

        # Some post optware dev script hooks
        [ -x /opt/etc/hooks/root.postopt ] && /opt/etc/hooks/root.postopt
        [ -x /opt/etc/hooks/user.postopt ] && su - calnex -c '/opt/etc/hooks/user.postopt'

        ;;
    reconfig)
        true
    ;;
    stop)
        echo "Shutting down Optware."
        true
    ;;
    *)
        echo "Usage: $0 {start|stop|reconfig}"
        exit 1
esac

exit 0
