#! /bin/sh

#########
if [ -z "$1" ] ; then
    case `echo "$0" | /bin/sed 's:^.*/\(.*\):\1:g'` in
        S??*) rc="add" ;;
        K??*) rc="remove" ;;
        *) rc="usage" ;;
    esac
else
    rc="$1"
fi

case "$rc" in
    add)
        REPO=`find /media -type f -name Packages -exec grep -l "\bendor\b" {} \; | sed 's/Packages//g' | sed s'/^\///'`
	if [ "$REPO" != "" ]
	then
	        su calnex -c "echo 'src/gz local file://'$REPO	> /opt/etc/ipkg/cross-feed.conf"
	fi
        ;;
    remove)
	su calnex -c "echo 'src/gz local file://srv/tftp/optware'	> /opt/etc/ipkg/cross-feed.conf"
        ;;
    *)
        echo "Usage: $0 (add|remove)"
        ;;
esac
