#! /bin/sh

#########
if [ -z "$1" ] ; then
    case `echo "$0" | /bin/sed 's:^.*/\(.*\):\1:g'` in
        S??*) rc="add" ;;
        K??*) rc="remove" ;;
        *) rc="usage" ;;
    esac
else
    rc="$1"
fi

case "$rc" in
    add)
        REPO=`find /media -type f -name Packages.gz | sed 's/Packages.gz/\*/g'`
	if [ $REPO -ne "" ]
	then
	        su calnex -c "echo $REPO	> /opt/etc/ipkg/cross-feed.conf"
	fi
        ;;
    remove)
	su calnex -c "echo 'src/gz cross http://packages.calnexsol.com/optware/__TARGET_DISTRO__/__TARGET_PRODUCT__'	> /opt/etc/ipkg/cross-feed.conf"
        ;;
    *)
        echo "Usage: $0 (add|remove)"
        ;;
esac
