#! /bin/sh

update_cross_feed() {
    repo=${1:-'home/.optware/srv/tftp/optware'}
    if [ "$(id -u)" -eq 0 ]; then
        su calnex -c "echo 'src/gz local file://${repo}' > /opt/etc/ipkg/cross-feed.conf"
    else
        echo "src/gz local file://${repo}" > /opt/etc/ipkg/cross-feed.conf
    fi
    return $?
}

#########
if [ -z "$1" ] ; then
    case $(echo "$0" | /bin/sed 's:^.*/\(.*\):\1:g') in
        S??*) rc="add" ;;
        K??*) rc="remove" ;;
        *) rc="usage" ;;
    esac
else
    rc="$1"
fi

case "$rc" in
    add)
        voodoo mount /dev/sdb /media/usb
        update_cross_feed $(find /media -type f -name Packages -exec grep -l "\bendor\b" {} \; | sed 's/Packages//g' | sed s'/^\///')
        ;;
    remove)
        voodoo umount /media/usb
        update_cross_feed
        ;;
    *)
        echo "Usage: $0 (add|remove)"
        ;;
esac
