#!/bin/sh

set -e

# Install the optware system
#echo 'root:$5$Hikksh95jH2sPpr$hScRAk6ZdfAsAjmrhqVGJSGF.86J6XYoXJgb1.L3Lu1' | /usr/sbin/chpasswd -e
echo 'calnex:c4ln3X' | /usr/sbin/chpasswd
mv /usr/bin/sudo /usr/bin/voodoo

