#!/bin/sh

export PATH=/opt/bin:/opt/sbin:$PATH

pghome="/opt/var/pgsql"
pgdata="$pghome/data"
pgver="$pghome/8.2"
pgdumpground="$pgver/dump"


echo ""
echo "POSTGRESQL POSTINST"
echo "==================="
echo "pghome:       ${pghome}"
echo ""
ls -l ${pghome}

echo "pgdata:       ${pgdata}"
ls -l ${pgdata}

echo "pgver:        ${pgver}"
ls -l ${pgver}

echo "pgdumpground: ${pgdumpground}"
ls -l ${pgdumpground}


echo "Process Dump"
ps aux

if [ ! -d $pghome ]
then
    mkdir -p $pghome
fi
if [ ! -d $pgdumpground ]
then
    mkdir -p $pgdumpground
fi

# initdb if not done before
dbinited=0
if [ -d $pgdata ]; then
    echo The $pgdata directory already exists
    dbinited=1
else
    echo "Initialize database ... "
    /opt/bin/initdb -D "$pgdata"
    [ -f $pgdata/PG_VERSION ] && echo "... database initialization done"
    dbinited=1
fi

# compatibility check and start db
echo "Listing /opt/etc/init.d/S95postgresql start"
cat /opt/etc/init.d/S95postgresql


echo "Calling database start"

#/opt/etc/init.d/S95postgresql start
/opt/bin/postmaster -D /opt/var/pgsql/data &


echo "Returned from call" 


if [ "$dbinited." = "1." -a -n "`pidof postmaster`" ]; then
    echo "Now database server is ready, you can test the connection by:"
    echo "	# su - postgres"
    echo "	$ /opt/bin/psql template1"
    echo "To allow access from other user, see http://www.postgresql.org/docs/8.2/interactive/sql-createuser.html"
    echo "To allow access from network, see http://developer.postgresql.org/docs/postgres/runtime-config.html#RUNTIME-CONFIG-CONNECTION"
fi

echo "Now doing postgress running loop"
echo "pgdata contains:"
ls -l $pgdata

echo "ls of root"
ls -l /

echo "ls of the tmp folder"
ls -l /tmp

pg_running=3
while [ $pg_running != 0 ]
do
    sleep 0.5
    pg_ctl status -D $pgdata
    pg_running=$?
done

ps aux

whoami

# Now loop waiting to see if we can connect via psql
#
psql_status=3
count=20
while [ ${psql_status} -ne 0 ] && [ ${count} -ne 0 ]
do
    echo "${count} iterations left..."
    echo "Checking database connection status... localhost"
    psql -h localhost -U calnex -d postgres -c "SELECT * FROM pg_catalog.pg_tables;"
    psql_status = $?
    echo "    psql localhost status ${psql_status}"

    echo "Checking database connection status... 127.0.0.1"
    psql -h 127.0.0.1 -U calnex -d postgres -c "SELECT * FROM pg_catalog.pg_tables;"
    psql_status=$?
    echo "    psql 127.0.0.1 status ${psql_status}"

    ps aux
    echo ""
    echo ""
    sleep 0.5
    count=$(expr $count - 1)
    echo ${count}
done


psql -h localhost -U calnex -d postgres -c "UPDATE pg_database SET datistemplate = FALSE WHERE datname = 'template1';"
psql -h localhost -U calnex -d postgres -c "DROP DATABASE template1;"
psql -h localhost -U calnex -d postgres -c "CREATE DATABASE template1 WITH TEMPLATE = template0 ENCODING = 'UNICODE';"
psql -h localhost -U calnex -d postgres -c "UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template1';"
psql -h localhost -U calnex -d template1 -c "VACUUM FREEZE;"

/opt/etc/init.d/S95postgresql stop