#!/bin/sh

if [ -f /opt/etc/init.d/S95postgresql ]; then
    /opt/etc/init.d/S95postgresql stop
    if [ -d /opt/var/pgsql/data_postgres-13 ]; then
        # Rename the PostgreSQL data directory
        if mv /opt/var/pgsql/data_postgres-13 /opt/var/pgsql/data; then
            echo "PostgreSQL data directory successfully restored."
        else
            echo "Deletion failed: Unable to restore PostgreSQL data directory."
        fi
    else
        echo "PostgreSQL 13 data directory does not exist, nothing to restore."
    fi
else
    /opt/etc/init.d/S91postgresql stop
    if [ -d /opt/var/pgsql/data ]; then
        # Rename the PostgreSQL data directory
        if mv /opt/var/pgsql/data /opt/var/pgsql/data_postgres-9.3.12; then
            echo "PostgreSQL 9 data directory successfully renamed."
        else
            echo "Deletion failed: Unable to remove PostgreSQL data directory."
        fi
    else
        echo "PostgreSQL 9 data directory does not exist, nothing to remove."
    fi
fi
sleep 1
