# Subroutine to create a file
#
#
CreateBundleVersionFile()
{
    /bin/cat << EOM > $2/Server/Software/Endor/BuildInformation/BundleVersion.cs

//
// This is autogenerated code - do not modify.  This function was created 
// by the release process.
//
//===================================================================================
// Copyright (c) Calnex Solutions Ltd.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===================================================================================
// The contents of this file should not be copied or distributed
// without permission being granted by Calnex Solutions Ltd.
//===================================================================================

namespace Calnex.Endor.Config
{
    /// <summary>
    /// Software bundle version information.
    /// </summary>
    internal static class VersionInformation
    {
        // We're constructing a string of the form aa.bb.cc
        //       aa.bb - major product version number (customer visible)
        //       cc    - minor build increment number (internal development releases)
        //
        // For a Windows install, aa.bb.cc must be updated in the ProductVersion property of the install tool.

#if ATTERO
        internal static string ApplicationVersion = "70.";
        internal static string BuildVersion = ApplicationVersion + "$1"
#else
        internal static string ApplicationVersion = "60.";
        internal static string BuildVersion = ApplicationVersion + "$1"
#endif

            + " (Nightly Build)";

    }
}
EOM

    return
}



[ -z "WORKSPACE" ] && { echo "Need to define WORKSPACE"; exit 1; }



# Now create the version file we want
# 
CreateBundleVersionFile `date +"%Y-%d-%m"` $1



# all done
#
exit 0



