#!/bin/sh

cd /opt/lib/endor
tar -xzf long-filepaths.tar.gz

#
# Unpack the CAT
# (take the CAT out of the bag?)
#
#mkdir ./CATLibs
#cd ./CATLibs
#tar -zxf ../cat.tar.gz
#cd ..

# Link the CAT into the folder structure at the correct place
#ln -s ./CATLibs/html CAT
#ln -s ./CATLibs/html/js js 

/opt/lib/ipkg/info/postgresql.postinst
echo "waiting for DB daemon to start"
echo "Product is ${PRODUCT}"
echo "This is the environment"
env
echo "End of environment display"
sleep 3
python3 /opt/lib/endor/schema/Baseline/RebuildDb_${PRODUCT}.py --superuser calnex --path /opt/lib/endor/schema/Baseline
/opt/etc/init.d/S95postgresql start
# /opt/etc/init.d/S96endor-virtualinstrument start
# /opt/etc/init.d/S97endor-instrumentcontroller start
# /opt/etc/init.d/S98cat-remotingserver start
# /opt/etc/init.d/S99endor-webapp start

