#!/bin/sh

/opt/etc/init.d/S99endor-webapp stop
/opt/etc/init.d/S98cat-remotingserver stop
/opt/etc/init.d/S97endor-instrumentcontroller stop

if [ -e /opt/etc/init.d/S96endor-virtualinstrument ]; then
    /opt/etc/init.d/S96endor-virtualinstrument stop
fi

sleep 1

cd /opt/lib/endor
unlink CAT
rm -f `tar -tzf long-filepaths.tar.gz`