#!/bin/sh

# Try to save any persistent data from the database
#
if [ -e /opt/lib/endor/utility/save_persistent_data.py ]; then
    echo "Saving persistent database settings"
    python3 /opt/lib/endor/utility/save_persistent_data.py > ${HOME}/endor_saved_state.txt
fi

/opt/etc/init.d/S99endor-webapp stop
/opt/etc/init.d/S98cat-remotingserver stop
/opt/etc/init.d/S97endor-instrumentcontroller stop

if [ -e /opt/etc/init.d/S96endor-virtualinstrument ]; then
    /opt/etc/init.d/S96endor-virtualinstrument stop
fi

sleep 1

rm -rf /opt/lib/endor/CAT
rm -f `tar -tzf long-filepaths.tar.gz`