#!/bin/sh

/opt/etc/init.d/S99endor-webapp stop
/opt/etc/init.d/S98cat-remotingserver stop
/opt/etc/init.d/S97endor-instrumentcontroller stop
/opt/etc/init.d/S96endor-virtualinstrument stop
sleep 1

cd /opt/lib/endor
rm -f `tar -tzf long-filepaths.tar.gz`
