#! /bin/bash

sleep 300

NET_IFACE_NAME=$(ls /sys/class/net | sed 's/lo//')
 echo "Detected interface: $NET_IFACE_NAME" >> /home/calnex/debug.txt

ip -br -f inet address | grep $NET_IFACE_NAME > /dev/null
if [[ $? != 0 ]]
then
  #ip addr add 192.168.10.10 dev enp0s3
  echo "Executing dhclient" >> /home/calnex/debug.txt
  dhclient
fi
