#! /bin/bash

echo "Starting loading server"

screen -dmS LOADING_HTTP_SERVER python3 /sbin/loading_server.py >/var/log/initserver.log
screen -dmS LOADING_HTTPS_SERVER python3 /sbin/loading_https_server.py >/var/log/initserver.log

LOADED=1
i=0

echo "Waiting for main server to be ready"

while [ $LOADED -ne "0" ]
do
	wget -qO- localhost:8000 > /dev/null
	LOADED=$?
    if [[ $LOADED -ne "0" ]]
    then
    curl -k https://localhost:8443 > /dev/null
    LOADED=$?
    fi	
	sleep 1
	((i++))
	if [[ $i -gt 2000 ]]
	then
		LOADED=0
	fi
done
