#! /bin/bash
echo 'Starting SystemConfig' >> /var/log/SystemConfig
echo 'Current PATH is $PATH' >> /var/log/SystemConfig
if [ ! -b /dev/sda3  ]
then
echo 'dev/sda3 not present' >> /var/log/SystemConfig
fdisk /dev/sda <<EOF1
n
p
3
4194368
20971583
t
3
82
w
EOF1
partprobe
mkswap /dev/sda3
else
echo 'dev/sda3 present' >> /var/log/SystemConfig
echo 'current PATH is $PATH ' >> /var/log/SystemConfig
swapon /dev/sda3
fi

if [ ! -b /dev/sda4  ]
then
echo 'dev/sda4 not present' >> /var/log/SystemConfig
fdisk /dev/sda <<EOF2
n
p
4
20971584

w
EOF2
partprobe
file -s /dev/sda4 | grep ext4
    if [[ $? != 0 ]]
    then
	echo 'On persistence detected' >> /var/log/SystemConfig
        mkfs.ext4 -L persistence /dev/sda4
        mkdir -p /mnt/home
        mount /dev/sda4 /mnt/home
        echo '/home union' >> /mnt/home/persistence.conf
        echo '/var/log union' >> /mnt/home/persistence.conf
        echo '/var/lib/dhcp union' >> /mnt/home/persistence.conf
        umount /mnt/home
        rm -rf /mnt/home
    fi
reboot
fi

## Check for previous Wheezy Install
if [ -d /run/live/persistence/sda4/home/calnex ]; then
        rm -rf /run/live/persistence/sda4/home/rw/calnex
        rm -rf /run/live/persistence/sda4/home/rw/.optware
        mv /run/live/persistence/sda4/home/calnex /run/live/persistence/sda4/home/rw
        mv /run/live/persistence/sda4/home/.optware /run/live/persistence/sda4/home/rw
        reboot
fi

echo 'Installing Debian' >> /var/log/SystemConfig
# Debian self install
if [[ -e /opt/var/lib/debian/root.img ]]
then
        cd /opt/var/lib/debian/
        OLD_PARTITION=$(fdisk -l /dev/sda | awk '$2 == "*" {print $1}')
        OLD_PARTITION="${OLD_PARTITION: -1}"
        if [ "$OLD_PARTITION" = "1" ]
        then
                NEW_PARTITION=2
                NEW_PARTITION_START=2099200
        else
                NEW_PARTITION=1
                NEW_PARTITION_START=2048
        fi
        LABEL_ROOT=$(blkid -s LABEL /dev/sda${OLD_PARTITION})
        LABEL_ROOT=${LABEL_ROOT##*\=}
        LABEL_IMG=$(blkid -s LABEL root.img)
        LABEL_IMG=${LABEL_IMG##*\=}
        if [ ${LABEL_ROOT} != ${LABEL_IMG} ]
        then
                gpg --ignore-time-conflict --no-default-keyring --keyring=/root/.gnupg/pubring.gpg --verify root.img.asc root.img 2>/dev/null 1>&2
                if [ $? = 0 ]
                then
IMG_SIZE=$(ls -l root.img | awk '{print $5}')

echo "Old OS ${LABEL_ROOT}"
echo "New OS ${LABEL_IMG}"
echo "New OS Size ${IMG_SIZE}"

# Delete partition, just to be sure
parted /dev/sda --script rm ${NEW_PARTITION} -- 2>/dev/null 1>&2
echo "Partition ${NEW_PARTITION} deleted"

partprobe
parted /dev/sda --script mkpart primary ${NEW_PARTITION_START}s $((${NEW_PARTITION_START} + ($IMG_SIZE/512)))s  -- 2>/dev/null 1>&2


fdisk /dev/sda << EOF4 2>/dev/null 1>&2
t
${NEW_PARTITION}
83
w
EOF4
echo "Partition ${NEW_PARTITION} created"

partprobe
dd if=root.img of=/dev/sda${NEW_PARTITION} 2>/dev/null 1>&2
echo "root.img installed"

sync
parted /dev/sda --script toggle ${NEW_PARTITION} boot -- 2>/dev/null 1>&2
echo "Partition ${NEW_PARTITION} marked as boot"

sync
reboot
                else
                        echo "Debian update image keysign check failed!"
                fi
        fi
fi

cp /opt/etc/cron.d/* /etc/cron.daily/

rm -rf /home/.optware/srv/tftp/optware
mkdir -p /home/.optware/srv/tftp
chown calnex /home/.optware/srv/tftp

# Create embedded log folder and ensure it is owned by the calnex user
if ! [ -d /home/.optware/var/lib/embedded/embedded_logs ]
then
    mkdir -p /home/.optware/var/lib/embedded/embedded_logs
fi
chown calnex:calnex -R /home/.optware/var/lib/embedded

# Setup persistant disk for logging on VM using liveCD
if test -b /dev/vda && ! test -d /home/calnex/Calnex100G/Persist; then 
  echo "Mounting persistent log directory /dev/vda1"
  mkdir -p /home/calnex/Calnex100G/Persist; 
  chown -R calnex:calnex /home/calnex/Calnex100G
  mount /dev/vda1 /home/calnex/Calnex100G/Persist; 

  echo "Linking LogFiles directory to persistent log directory"
  if test -d /home/calnex/Calnex100G/Logs/; then
    rm -rf /home/calnex/Calnex100G/Logs
  fi
  su - calnex -c 'ln -s /home/calnex/Calnex100G/Persist /home/calnex/Calnex100G/Logs'
fi

## Setup cGroups
mkdir -p /dev/cgroups
mount -t cgroup -omemory memory /dev/cgroups

# Setup a limited memory control group
mkdir -p /dev/cgroups/limited
chmod go+w /dev/cgroups/limited/tasks

total_mem=$(awk '/MemTotal/{print $2}' /proc/meminfo)
if [ "$total_mem" -lt 5242880 ]; then
  # Assuming a 4GB memory setup, so assign 2GB to limited group
  echo 2147483648 > /dev/cgroups/limited/memory.limit_in_bytes
else
  # Assuming a 16GB setup, so assign 12GB to limited group
  echo 12884901888 > /dev/cgroups/limited/memory.limit_in_bytes
fi

/sbin/ip_fallback &
