#! /bin/bash
echo 'Starting S01SystemConfig' | tee -a /var/log/SystemConfig
echo "Current PATH is $PATH" | tee -a /var/log/SystemConfig
  
cp /opt/etc/cron.d/* /etc/cron.daily/

# Setup tftp serve directory
rm -rf /home/.optware/srv/tftp/optware
mkdir -p /home/.optware/srv/tftp
chown calnex /home/.optware/srv/tftp

# Clean out old journals
find /var/log/journal -type f -mtime +1 -exec rm {} \;
find /var/log/journal -mindepth=1 -empty -type d -delete

# Create embedded log folder and ensure it is owned by the calnex user
if ! [ -d /home/.optware/var/lib/embedded/embedded_logs ]
then
  mkdir -p /home/.optware/var/lib/embedded/embedded_logs
fi
chown calnex:calnex -R /home/.optware/var/lib/embedded

mkdir -p /home/.optware/etc/hooks
chown calnex:calnex /home/.optware/etc/hooks

# Setup persistant disk for logging on VM using liveCD
if test -b /dev/vda && ! test -d /home/calnex/Calnex100G/Persist; then 
  echo "Mounting persistent log directory /dev/vda1" | tee -a /var/log/SystemConfig
  mkdir -p /home/calnex/Calnex100G/Persist; 
  chown -R calnex:calnex /home/calnex/Calnex100G
  mount /dev/vda1 /home/calnex/Calnex100G/Persist; 

  echo "Linking LogFiles directory to persistent log directory"
  if test -d /home/calnex/Calnex100G/Logs/; then
    rm -rf /home/calnex/Calnex100G/Logs
  fi
  su - calnex -c 'ln -s /home/calnex/Calnex100G/Persist /home/calnex/Calnex100G/Logs'
fi

/sbin/ip_fallback &
