#! /bin/bash

echo "### Output of /etc/network/interfaces" >> /home/calnex/debug.txt

if [ -f /etc/network/interfaces ]; then
    echo "*** Modifying Interfaces file" >> /home/calnex/debug.txt
    sed -i 's/inet dhcp/inet manual/' /etc/network/interfaces
    cat /etc/network/interfaces >> /home/calnex/debug.txt
else
    echo "*** No Interfaces file found" >> /home/calnex/debug.txt
fi
