#!/bin/bash

IFACECFG=/etc/network/interfaces
if [ -f $IFACECFG ]; then
    
	#Make sure the first interface is manual
	sed -i 's/inet dhcp/inet manual/' $IFACECFG
	
	# Make sure embedded link is there, if its missing add it
	search_string="iface enp6s0 inet static"
	if ! grep -q "$search_string" "$IFACECFG"; then
		echo -e "\n\nallow-hotplug enp6s0\niface enp6s0 inet static\naddress 10.10.10.11\nnetmask 255.255.255.254" >> $IFACECFG
	fi
fi
